/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import projetcinema.Cinema;

/**
 *
 * @author tjrha
 */
public class FRechercherC extends javax.swing.JDialog {

    /**
     * Creates new form FRechercherC
     */
    
    
    private JTable table;
    //private JTable table2;
    //private JScrollPane scrollPane;
//    private String[] columns = new String[4];
//    private String[][] data = new String[4][((FAccueil) this.getParent()).getPortail().getTailleListeCinema()] ;
//    JButton button = new JButton();
    
     
    public FRechercherC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    public void init(){
        
        DefaultListModel liste = new DefaultListModel();
        for(int i=0;i<((FAccueil) this.getParent()).getPortail().getTailleListeCinema();i++){
            liste.add(i,((FAccueil) this.getParent()).getPortail().getCinema().get(i).getId()+" | "+((FAccueil) this.getParent()).getPortail().getCinema().get(i).getVille()+" | "+((FAccueil) this.getParent()).getPortail().getCinema().get(i).getCoordonne());
        }
        lCinema.setModel(liste);
        System.out.println(lCinema.getSelectedValue());
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lRechNom = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bRetour = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lCinema = new javax.swing.JList<>();
        lRechNom1 = new javax.swing.JLabel();
        tfRechVille = new javax.swing.JTextField();
        bEntrer = new javax.swing.JButton();

        lRechNom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lRechNom.setForeground(new java.awt.Color(255, 255, 255));
        lRechNom.setText("Rechercher par Nom :");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        bRetour.setBackground(new java.awt.Color(204, 0, 0));
        bRetour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRetour.setForeground(new java.awt.Color(255, 255, 255));
        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        lCinema.setBackground(new java.awt.Color(102, 102, 102));
        lCinema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCinema.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(lCinema);

        lRechNom1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lRechNom1.setForeground(new java.awt.Color(255, 255, 255));
        lRechNom1.setText("Rechercher par Nom :");

        tfRechVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRechVilleActionPerformed(evt);
            }
        });

        bEntrer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bEntrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/Loupe.png"))); // NOI18N
        bEntrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRetour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lRechNom1)
                        .addGap(18, 18, 18)
                        .addComponent(tfRechVille, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEntrer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEntrer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRechVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lRechNom1)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(bRetour)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        this.getParent().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    private void tfRechVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRechVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRechVilleActionPerformed

    private void bEntrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrerActionPerformed
        // TODO add your handling code here:
        String ville = tfRechVille.getText();
        ArrayList<Cinema> Cinema = ((FAccueil) this.getParent()).getPortail().rechercherCinema(ville);
        DefaultListModel liste = new DefaultListModel();
        for(int i=0;i<Cinema.size();i++){
            liste.add(i,Cinema.get(i).getId()+" | "+Cinema.get(i).getVille()+" | "+Cinema.get(i).getCoordonne());
        }
        lCinema.setModel(liste);
    }//GEN-LAST:event_bEntrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRechercherC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRechercherC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRechercherC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRechercherC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRechercherC dialog = new FRechercherC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrer;
    private javax.swing.JButton bRetour;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lCinema;
    private javax.swing.JLabel lRechNom;
    private javax.swing.JLabel lRechNom1;
    private javax.swing.JTextField tfRechVille;
    // End of variables declaration//GEN-END:variables
}
